name: Test GCD Script

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run the GCD script test
      run: chmod +x ./test_gcd.sh && ./test_gcd.sh

