name: Test GCD Script

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Grant execute permission
      run: chmod +x gcd.sh test_gcd.sh

    - name: Run the GCD script test
      run: ./test_gcd.sh

